test_multi_target_workspace_custom_derived_data_path test added to check the XCODEBUILD_OPTIONS input.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -13,6 +13,7 @@ app:
 workflows:
   test_objc:
     envs:
+    - XCODEBUILD_OPTIONS:
     - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-apps-ios-simple-objc.git
     - BRANCH: master
     - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
@@ -38,6 +39,7 @@ workflows:
     - errcheck:
     - go-test:
     envs:
+    - XCODEBUILD_OPTIONS:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
     - COMMIT: "52ca16a9cead25be8c95c54e7fd53ce8fd945330"
     - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
@@ -56,6 +58,7 @@ workflows:
     before_run:
     # - test_xcode_8
     envs:
+    - XCODEBUILD_OPTIONS:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
     - COMMIT: "ab36ed563bbc3125118e9f27df91474822dc0d46"
     - BITRISE_PROJECT_PATH: code-sign-test.xcodeproj
@@ -72,6 +75,7 @@ workflows:
     before_run:
     - test_multi_target
     envs:
+    - XCODEBUILD_OPTIONS:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-workspace-swift.git
     - BRANCH: master
     - BITRISE_PROJECT_PATH: sample-apps-ios-workspace-swift.xcworkspace
@@ -84,10 +88,27 @@ workflows:
     after_run:
     - _common
 
+  test_multi_target_workspace_custom_derived_data_path:
+    envs:
+    - XCODEBUILD_OPTIONS: "-derivedDataPath ./ddata"
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-workspace-swift.git
+    - BRANCH: watch
+    - BITRISE_PROJECT_PATH: sample-apps-ios-workspace-swift.xcworkspace
+    - BITRISE_SCHEME: sample-apps-ios-workspace-swift
+    - SIMULATOR_OS_VERSION: "11.4"
+    - OUTPUT_TOOL: xcpretty
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED: ""
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: ""
+    after_run:
+    - _common
+    - test_multi_target_workspace
+
   test_multi_target_workspace:
     before_run:
     - test_workspace
     envs:
+    - XCODEBUILD_OPTIONS:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-workspace-swift.git
     - BRANCH: watch
     - BITRISE_PROJECT_PATH: sample-apps-ios-workspace-swift.xcworkspace
@@ -149,18 +170,26 @@ workflows:
             #!/bin/bash
             set -e
 
-            if [ $BITRISE_APP_DIR_PATH != $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED ] ; then
-              echo "[!] Missing Exported Artifact: should have:\n$BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED and have\n$BITRISE_APP_DIR_PATH"
-              exit 1
-            else
-              echo "BITRISE_APP_DIR_PATH -> $BITRISE_APP_DIR_PATH"
+            if [ -z ${BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED} ] ; then
+              echo BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED is empty  
+            else 
+              if [ -z ${BITRISE_APP_DIR_PATH+x} ] || [ ${BITRISE_APP_DIR_PATH+x} != ${BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED+x} ] ; then
+                echo "[!] Missing Exported Artifact: should have: $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_EXPECTED and have: $BITRISE_APP_DIR_PATH"
+                exit 1
+              else
+                echo "BITRISE_APP_DIR_PATH -> $BITRISE_APP_DIR_PATH"
+              fi
             fi
 
-            if [ $BITRISE_APP_DIR_PATH_LIST != $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED ] ; then
-              echo "[!] Missing Exported Artifact: should have:\n$BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED and have\n$BITRISE_APP_DIR_PATH_LIST"
-              exit 1
-            else
-              echo "BITRISE_APP_DIR_PATH_LIST -> $BITRISE_APP_DIR_PATH_LIST"
+            if [ -z ${BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED} ] ; then
+              echo BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED is empty  
+            else 
+              if [ -z ${BITRISE_APP_DIR_PATH_LIST+x} ] || [ ${BITRISE_APP_DIR_PATH_LIST+x} != ${BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED+x} ] ; then
+                echo "[!] Missing Exported Artifact: should have: $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED and have: $BITRISE_APP_DIR_PATH_LIST"
+                exit 1
+              else
+                echo "BITRISE_APP_DIR_PATH_LIST -> $BITRISE_APP_DIR_PATH_LIST"
+              fi
             fi
 
   # ----------------------------------------------------------------
