-

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -8,35 +8,109 @@ app:
   - BITRISE_STEP_GIT_CLONE_URL: https://github.com/bitrise-steplib/steps-xcode-archive-for-simulator.git
   - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
 
+  - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
+
 workflows:
-  test:
-    before_run:
-    - audit-this-step
+  test_objc:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-apps-ios-simple-objc.git
+    - COMMIT: "65cd120bf4459c2881cfe2b731395b4efc53855d"
+    - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
+    - BITRISE_SCHEME: ios-simple-objc
+    - XCODEBUILD_OPTIONS: 'CODE_SIGN_IDENTITY="iPhone Developer: Bitrise Bot"'
+    - OUTPUT_TOOL: xcodebuild
+    after_run:
+    - _common
+
+  test_xcode_7:
+    steps:
+    - go-list:
+    - go-test:
+    after_run:
+    - test_objc
+    - _common
+
+  test_xcode_8:
     steps:
     - go-list:
     - golint:
     - errcheck:
     - go-test:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
+    - COMMIT: "52ca16a9cead25be8c95c54e7fd53ce8fd945330"
+    - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
+    - BITRISE_SCHEME: ios-xcode-8.0
+    - OUTPUT_TOOL: xcpretty
+    after_run:
+    - test_objc
+    - _common
+
+  test_multi_target:
+    before_run:
+    - test_xcode_8
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
+    - COMMIT: "ab36ed563bbc3125118e9f27df91474822dc0d46"
+    - BITRISE_PROJECT_PATH: code-sign-test.xcodeproj
+    - BITRISE_SCHEME: code-sign-test
+    - XCODEBUILD_OPTIONS: 'CODE_SIGN_IDENTITY="iPhone Developer: Bitrise Bot"'
+    after_run:
+    - _common
+
+  _common:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            rm -rf "$ORIG_BITRISE_SOURCE_DIR/_tmp"
+            mkdir -p "$ORIG_BITRISE_SOURCE_DIR/_tmp"
     - change-workdir:
-        title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
+        title: Switch working dir to _tmp dir
         run_if: true
         inputs:
-        - path: ./_tmp
+        - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
         - is_create_path: true
-    - path::./:
-        title: Step Test
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
-        run_if: true
+    - script:
         inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+            
+    - certificate-and-profile-installer:
+    - path::./:
+        inputs:
+        - output_tool: xcodebuild
+        - xcodebuild_options: $XCODEBUILD_OPTIONS
+        - verbose_log: "yes"
+    - script:
+        title: Output (generated by the Step) tests
+        is_always_run: true
+        inputs:
+        - content: |-
+            echo "-> BITRISE_IPA_PATH:           $BITRISE_IPA_PATH"
+            echo "-> BITRISE_DSYM_PATH:          $BITRISE_DSYM_PATH"
+            echo "-> BITRISE_XCARCHIVE_ZIP_PATH: $BITRISE_XCARCHIVE_ZIP_PATH"
+
+            echo "-> BITRISE_APP_DIR_PATH:               $BITRISE_APP_DIR_PATH"
+            echo "-> BITRISE_DSYM_DIR_PATH:              $BITRISE_DSYM_DIR_PATH"
+            echo "-> BITRISE_XCARCHIVE_PATH:             $BITRISE_XCARCHIVE_PATH"
+            echo "-> BITRISE_IDEDISTRIBUTION_LOGS_PATH:  $BITRISE_IDEDISTRIBUTION_LOGS_PATH"
+            echo "-> BITRISE_XCODE_RAW_RESULT_TEXT_PATH: $BITRISE_XCODE_RAW_RESULT_TEXT_PATH"
 
   # ----------------------------------------------------------------
   # --- Utility workflows
