PR clean - fix + output check added

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -19,6 +19,8 @@ workflows:
     - BITRISE_SCHEME: ios-simple-objc
     - OUTPUT_TOOL: xcodebuild
     - SIMULATOR_OS_VERSION: "latest"
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: $BITRISE_DEPLOY_DIR'/ios-simple-objc.app'
     after_run:
     - _common
 
@@ -41,6 +43,8 @@ workflows:
     - BITRISE_SCHEME: ios-xcode-8.0
     - OUTPUT_TOOL: xcpretty
     - SIMULATOR_OS_VERSION: latest
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: $BITRISE_DEPLOY_DIR'/'ios-xcode-8.0.app
     before_run:
     - test_objc
     after_run:
@@ -48,7 +52,7 @@ workflows:
 
   test_multi_target:
     before_run:
-    - test_xcode_8
+    # - test_xcode_8
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
     - COMMIT: "ab36ed563bbc3125118e9f27df91474822dc0d46"
@@ -56,6 +60,8 @@ workflows:
     - BITRISE_SCHEME: code-sign-test
     - SIMULATOR_OS_VERSION: "latest"
     - OUTPUT_TOOL: xcpretty
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: "$BITRISE_DEPLOY_DIR/code-sign-test.app|$BITRISE_DEPLOY_DIR/watchkit-app.app"
     after_run:
     - _common
 
@@ -69,6 +75,8 @@ workflows:
     - BITRISE_SCHEME: sample-apps-ios-workspace-swift
     - SIMULATOR_OS_VERSION: "latest"
     - OUTPUT_TOOL: xcpretty
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: "$BITRISE_DEPLOY_DIR/sample-apps-ios-workspace-swift.app"
     after_run:
     - _common
 
@@ -80,8 +88,10 @@ workflows:
     - BRANCH: watch
     - BITRISE_PROJECT_PATH: sample-apps-ios-workspace-swift.xcworkspace
     - BITRISE_SCHEME: sample-apps-ios-workspace-swift
-    - SIMULATOR_OS_VERSION: "latest"
+    - SIMULATOR_OS_VERSION: "11.3"
     - OUTPUT_TOOL: xcpretty
+    - OUTPUT_DIR: $BITRISE_DEPLOY_DIR
+    - BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED: "$BITRISE_DEPLOY_DIR/sample-apps-ios-workspace-swift.app|$BITRISE_DEPLOY_DIR/watchkit-app.app"
     after_run:
     - _common
 
@@ -128,11 +138,18 @@ workflows:
         - xcodebuild_options: $XCODEBUILD_OPTIONS
         - verbose_log: "no"
     - script:
-        title: Output (generated by the Step) tests
-        is_always_run: true
+        title: Output check
         inputs:
         - content: |-
-            echo "-> BITRISE_XCODE_RAW_RESULT_TEXT_PATH: $BITRISE_XCODE_RAW_RESULT_TEXT_PATH"
+            #!/bin/bash
+            set -e
+
+            if [ $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP != $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED ] ; then
+              echo "[!] Missing Exported Artifact: should have:\n$BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP_EXPECTED and have\n$BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP"
+              exit 1
+            else
+              echo "BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP -> $BITRISE_EXPORTED_SIMULATOR_BUILDS_PATH_MAP"
+            fi
 
   # ----------------------------------------------------------------
   # --- Utility workflows
